<?php

require_once 'commonDao.php';
CommonDao::requireFileIn('/../entity/', 'stat.php');
CommonDao::requireFileIn('/../entity/', 'statLine.php');

class StatDao {

  public function getMaxWeek() {
    CommonDao::connectToDb();
    $query = "select max(week) from chef_stat";
    $res = mysql_query($query);
    $row = mysql_fetch_row($res);
    return $row[0];
  }

  /**
   * Returns a single stat line for the specified player during the specified year and null if
   * it doesn't exist.
   */
  public static function getStatLineForChefWeek(Chef $chef, $week) {
    CommonDao::connectToDb();
    $query = "select cs.*, s.*
    	      from chef_stat cs, stat s
    	      where cs.week = $week and cs.chef_id = " . $chef->getId() .
            " and cs.stat_id = s.stat_id";

    return StatDao::createStatLineFromQuery($query, $chef, $week);
  }

  private static function createStatLineFromQuery($query, $chef, $week) {
    $res = mysql_query($query);

    if (mysql_num_rows($res) == 0) {
      return null;
    }

    $statLine = new StatLine(-1, $week, $chef->getId(), null);
    $statsDb = array();
    while($statDb = mysql_fetch_assoc($res)) {
      $statsDb[] = StatDao::populateStat($statDb);
    }
    $statLine->setStats($statsDb);
    return $statLine;
  }

  private static function populateStat($statDb) {
    return new Stat($statDb["stat_id"], $statDb["name"], $statDb["points"],
        $statDb["abbreviation"]);
  }

  /**
   * Returns the total fantasy points generated by the specified chef
   */
  public static function getTotalPointsByChef(Chef $chef) {
    CommonDao::connectToDb();
    $query = "select sum(s.points)
              from stat s, chef_stat cs
              where cs.chef_id = " . $chef->getId() .
            " and cs.stat_id = s.stat_id";
    $res = mysql_query($query);
    $row = mysql_fetch_row($res);
    return $row[0];
  }

  /**
  * Returns the total fantasy points generated by chefs for the specified team.
  */
  public static function getTotalPointsByTeam(Team $team) {
    CommonDao::connectToDb();
    $query = "select sum(s.points)
                from stat s, chef_stat cs, team_chef tc
                where tc.team_id = " . $team->getId() . " and tc.chef_id = cs.chef_id
                and cs.stat_id = s.stat_id";
    $res = mysql_query($query);
    $row = mysql_fetch_row($res);
    return $row[0];
  }


  /**
   * Returns all of the stats
   */
  public static function getAllStats() {
    CommonDao::connectToDb();
    $query = "select *
              from stat
              order by stat_id";
    return StatDao::createStatsFromQuery($query);
  }

  private static function createStatsFromQuery($query) {
    $res = mysql_query($query);
    $statsDb = array();
    while($statDb = mysql_fetch_assoc($res)) {
      $statsDb[] = StatDao::populateStat($statDb);
    }
    return $statsDb;
  }
}
?>